### ISSUE TITLE
you should probably demand node

### ISSUE THREAD

**Issue by bryanmacfarlane** [hinzo/vso-task-hockeyapp#1]
The task.json demands section should probably demand node.  For xplat, it will just be there but on windows agent, node isn't necessarily installed but you call via the ps1 wrapper.  If you demand node and it's not installed on the windows agent, they will get a helpful prompt that their agent needs node

**Comment by hinzo** [comment]
makes sense. thanks

**Comment by hinzo** [comment]
resolved with d0d2eec6073db170f88b010d2c08491ed7a489f9
